services:
  broker:
    image: redis:7
    restart: unless-stopped

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: Y&JkD6QWAre&T4F&

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - .volumes/paperless-ngx/data:/usr/src/paperless/data
      - .volumes/paperless-ngx/media:/usr/src/paperless/media
      - .volumes/paperless-ngx/consume:/usr/src/paperless/consume
      - .volumes/paperless-ngx/export:/usr/src/paperless/export
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: Y&JkD6QWAre&T4F&
      PAPERLESS_SECRET_KEY: "NlbAa0tvP2Bq6HDZsyXAzUth77oAXTbL2MIqWbLp6qw="
      PAPERLESS_TIME_ZONE: "Europe/Paris"
      PAPERLESS_OCR_LANGUAGE: "fra+eng"
      PAPERLESS_URL: "https://paperless.sparta.diskstation.me"
      PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://paperless.sparta.diskstation.me"
      PAPERLESS_ALLOWED_HOSTS: "https://paperless.sparta.diskstation.me"
      PAPERLESS_CORS_ALLOWED_HOSTS: "https://paperless.sparta.diskstation.me"
      PAPERLESS_TRUSTED_PROXIES: "https://paperless.sparta.diskstation.me"
      USERMAP_UID: 1000
      USERMAP_GID: 1000
